Repository finos/git-proxy, pull requests merged in 2024-05, with the labels that each got.

#549 Remove auth headers from bare git clone on server
  package.json
  src/proxy/processors/push-action/pullRemote.js
  website/docs/installation.mdx
  website/docusaurus.config.js
Labels: security

#555 ci(fix): Limit when the releaser is run
  .github/workflows/release.yml
Labels: automation

#556 chore(ci): update template name and github release markdown format
  .github/release-drafter.yml
Labels: documentation, maintenance

#554 ci(fix): Remove NPM step condition
  .github/workflows/release.yml
Labels: fix, automation

#560 chore(ci): update release.yml paths to include package.json and package-lock.json
  .github/workflows/release.yml
Labels: maintenance

#565 chore(ci): disable auto release until auto version bumping implemented
  .github/workflows/release.yml
Labels: bug, maintenance

#575 chore: add npm run build step to CI workflow
  .github/workflows/npm.yml
Labels: maintenance

#578 fix: ensure npm publish includes build directory
  .npmignore
Labels: fix

#583 chore(release): v1.2.3
  package-lock.json
  package.json
Labels: maintenance

#584 chore(docs): typos and documentation adjustments
  website/README.md
  website/docs/installation.mdx
  website/docs/quickstart/approve.mdx
  website/docs/usage.mdx
  website/docusaurus.config.js
Labels: maintenance
