Repository finos/git-proxy, pull requests merged in 2024-06, with the labels that each got.

#558 feat: add https support #546
  certs/cert.pem
  certs/create-cert.sh
  certs/key.pem
  src/config/env.js
  src/config/index.js
  src/proxy/index.js
  test/testConfig.test.js
  website/docs/configuration/overview.mdx
  website/docs/quickstart/intercept.mdx
Labels: feature

#591 chore: v1.3.1 🎉
  package-lock.json
  package.json
Labels: dependencies, maintenance

#581 test: introduce UI tests with Cypress
  .github/workflows/ci.yml
  cypress.config.js
  cypress/e2e/login.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/ui/views/Login/Login.jsx
Labels: automation

#592 chore: added a CI step to detect unused dependencies
  .github/workflows/dependency-review.yml
  .github/workflows/unused-dependencies.yml
Labels: maintenance

#612 docs: create a community and social media wall on the website
  website/docusaurus.config.js
  website/package.json
  website/src/css/custom.css
  website/src/pages/index.js
  website/src/pages/testimonials.js
  website/yarn.lock
Labels: documentation

#623 chore: v1.3.2
  package-lock.json
  package.json
Labels: maintenance

#622 chore: add demo video to docs site and README
  README.md
  website/package.json
  website/src/pages/index.js
  website/yarn.lock
Labels: maintenance

#618 docs: replaced "Git Proxy" with "GitProxy"
  README.md
  website/docs/configuration/overview.mdx
  website/docs/configuration/reference.mdx
  website/docs/index.mdx
  website/docs/installation.mdx
  website/docs/quickstart/approve.mdx
  website/docs/quickstart/intercept.mdx
  website/docs/usage.mdx
  website/docusaurus.config.js
  website/src/pages/index.js
Labels: documentation

#626 chore: propagate renaming to remaining files
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  certs/create-cert.sh
  config.schema.json
  index.html
  packages/git-proxy-cli/index.js
  packages/git-proxy-cli/package.json
  packages/git-proxy-cli/test/testCliUtils.js
  scripts/doc-schema.js
  src/plugin.js
  src/proxy/processors/push-action/blockForAuth.js
  src/ui/components/Footer/Footer.jsx
Labels: documentation, maintenance
