Repository finos/git-proxy, pull requests merged in 2024-08, with the labels that each got.

#672 chore: v1.3.4
  package-lock.json
  package.json
Labels: maintenance

#676 chore: create scorecard.yml
  .github/workflows/scorecard.yml
  README.md
Labels: maintenance

#678 fix: resolve build error on arm64 machine
  package-lock.json
  package.json
Labels: fix

#706 feat: add google analytics docusaurus plugin
  website/docusaurus.config.js
  website/package.json
Labels: feature
