Repository finos/git-proxy, pull requests merged in 2024-11, with the labels that each got.

#782 fix: Update pullRemote.js to set appropriate directory permissions
  src/proxy/processors/push-action/pullRemote.js
Labels: fix

#786 fix: adjust auth processor to use custom service url
  src/proxy/processors/push-action/blockForAuth.js
  src/service/routes/repo.js
  src/service/urls.js
  test/proxyURL.test.js
Labels: fix

#784 fix: update server start script for cross-platform compatibility
  package.json
Labels: fix

#787 chore: version bump patch to 1.5.1
  package-lock.json
  package.json
Labels: maintenance

#789 feat: format violation text output on a blocked push
  package.json
  src/proxy/processors/push-action/getDiff.js
  src/proxy/processors/push-action/scanDiff.js
  test/scanDiff.test.js
Labels: feature

#790 chore: version bump patch to v1.5.2
  package-lock.json
  package.json
Labels: maintenance

#792 fix: sync issue between dependency manifest in package-lock.json and package.json
  package-lock.json
Labels: fix

#793 refactor: remove exports from package.json and adjust imports
  package.json
  plugins/git-proxy-plugin-samples/example.cjs
  plugins/git-proxy-plugin-samples/index.js
  test/fixtures/test-package/default-export.js
  test/fixtures/test-package/multiple-export.js
  test/fixtures/test-package/package.json
  test/fixtures/test-package/subclass.js
  website/docs/development/plugins.mdx
Labels: automation

#795 chore: bump minor version to 1.6.0
  package-lock.json
  package.json
Labels: maintenance

#807 chore: bump version by minor to v1.7.0
  package-lock.json
  package.json
Labels: maintenance
