Repository finos/git-proxy, pull requests merged in 2024-10, with the labels that each got.

#720 chore: move from bcrypt to bcryptjs
  package-lock.json
  package.json
  src/db/index.js
  src/service/passport/local.js
  test/testUserCreation.test.js
Labels: maintenance, feature

#728 chore: bump minor to v1.3.5
  package-lock.json
  package.json
Labels: dependencies, maintenance

#639 refactor: code clone component
  src/ui/components/CustomButtons/CodeActionButton.jsx
  src/ui/views/RepoDetails/RepoDetails.jsx
  src/ui/views/RepoList/Components/RepoOverview.jsx
Labels: automation

#731 chore: bump minor to v1.3.6
  package-lock.json
  package.json
Labels: maintenance

#735 fix: #669-ui/docs: clone component is undefined when running as a server
  src/ui/views/RepoList/Components/RepoOverview.jsx
Labels: fix

#736 chore: bump minor to v1.3.7
  package-lock.json
  package.json
Labels: maintenance

#742 fix: allow all default config to be replaced by user config
  src/config/index.js
Labels: fix

#744 chore: bump minor to v1.3.8
  package-lock.json
  package.json
Labels: maintenance

#746 chore: Add repository in package.json files
  package.json
  packages/git-proxy-cli/package.json
  packages/git-proxy-notify-hello/package.json
Labels: maintenance

#741 chore: dont leak password from server
  src/db/mongo/users.js
  src/service/routes/auth.js
  test/testLogin.test.js
Labels: maintenance

#750 fix: move creation of remote folder into function call
  src/proxy/processors/push-action/pullRemote.js
Labels: bug, fix

#751 chore: bump patch version to 1.3.9
  package-lock.json
  package.json
Labels: maintenance

#753 chore: bump patch version to 1.3.10
  package-lock.json
  package.json
Labels: maintenance

#713 feat: expose plugin extension points into main package, developer docs + sample
  .npmignore
  config.schema.json
  package-lock.json
  package.json
  packages/git-proxy-notify-hello/index.js
  plugins/README.md
  plugins/git-proxy-plugin-samples/example.cjs
  plugins/git-proxy-plugin-samples/index.js
  plugins/git-proxy-plugin-samples/package.json
  proxy.config.json
  scripts/doc-schema.js
  src/config/index.js
  src/plugin.js
  src/proxy/actions/index.js
  src/proxy/chain.js
  src/proxy/index.js
  src/proxy/routes/index.js
  test/chain.test.js
  test/fixtures/baz.js
  test/fixtures/test-package/default-export.js
  test/fixtures/test-package/multiple-export.js
  test/fixtures/test-package/package.json
  test/fixtures/test-package/subclass.js
  test/plugin.test.js
  test/testPluginLoader.test.js
  website/docs/configuration/reference.mdx
  website/docs/development/contributing.mdx
  website/docs/development/plugins.mdx
  website/sidebars.js
Labels: feature

#756 chore: move dev dependencies to the right section
  package-lock.json
  package.json
Labels: maintenance

#757 chore: bump minor for release v1.4.0
  package-lock.json
  package.json
Labels: maintenance

#748 fix: fixed hover effect
  website/src/css/custom.css
Labels: fix

#777 chore: bump patch to 1.4.1
  package-lock.json
  package.json
Labels: maintenance

#778 chore: bump minor to 1.5.0
  package-lock.json
  package.json
Labels: maintenance
