Repository finos/git-proxy, pull requests merged in 2024-07, with the labels that each got.

#632 chore: add all maintainers & contributors to docs site ❇️
  website/docusaurus.config.js
  website/package.json
  website/src/pages/index.js
  website/yarn.lock
Labels: documentation, maintenance

#645 chore: deprecate CVE Node scanning workflow
  .github/workflows/cve-scanning-node.yml
Labels: maintenance

#648 docs: adding Zoom meeting and mailing list to README
  README.md
Labels: documentation, maintenance

#649 docs: install a local checkout
  website/docs/installation.mdx
Labels: documentation

#666 chore: v1.3.3
  package-lock.json
  package.json
Labels: maintenance
