Repository finos/git-proxy, pull requests merged in 2025-05, with the labels that each got.

#999 feat: rate limiter config
  config.schema.json
  proxy.config.json
  src/config/index.ts
  src/config/types.ts
  src/service/index.js
  test/testConfig.test.js
  website/docs/configuration/reference.mdx
Labels: feature

#1006 feat: report illegal commit messages
  src/proxy/processors/push-action/checkCommitMessages.ts
Labels: feature

#1007 ci: generate js and definitions from ts and place in original location
  .github/workflows/ci.yml
  .github/workflows/npm.yml
  .npmignore
  package.json
  scripts/build-for-publish.sh
  scripts/undo-build.sh
  src/proxy/index.ts
  tsconfig.json
  tsconfig.publish.json
Labels: automation

#1009 chore: bump by minor to v1.12.0
  package-lock.json
  package.json
Labels: maintenance

#1012 docs(readme): fix markdown in README
  README.md
Labels: documentation

#1010 feat: integrate gitleaks
  src/proxy/chain.ts
  src/proxy/processors/push-action/gitleaks.ts
  src/proxy/processors/push-action/index.ts
  test/chain.test.js
Labels: feature

#1013 chore: bump by minor to v1.13.0
  package-lock.json
  package.json
Labels: maintenance

#1014 chore: create meeting_minutes.md
  .github/ISSUE_TEMPLATE/meeting_minutes.md
Labels: maintenance

#935 feat: implements config loader to enable remote or external configs
  .gitignore
  config.schema.json
  package.json
  packages/git-proxy-cli/index.js
  proxy.config.json
  src/config/ConfigLoader.ts
  src/config/index.ts
  src/proxy/chain.ts
  src/proxy/index.ts
  src/service/index.js
  test/ConfigLoader.test.js
  test/chain.test.js
  website/docs/configuration/overview.mdx
  website/docs/configuration/reference.mdx
Labels: feature

#1021 chore: bump by minor to v1.14.0
  package-lock.json
  package.json
Labels: maintenance

#1034 chore: bump by minor to v1.15.0
  package-lock.json
  package.json
Labels: maintenance

#963 feat: enable multiple auth methods
  cypress/e2e/login.cy.js
  package-lock.json
  package.json
  proxy.config.json
  src/config/index.ts
  src/service/passport/activeDirectory.js
  src/service/passport/index.js
  src/service/passport/local.js
  src/service/passport/oidc.js
  src/service/routes/auth.js
  src/ui/components/RouteGuard/RouteGuard.tsx
  src/ui/views/RepoList/Components/RepoOverview.jsx
  test/testAuthMethods.test.js
  test/testConfig.test.js
  test/testLogin.test.js
  website/docs/quickstart/approve.mdx
  website/docs/quickstart/intercept.mdx
Labels: feature

#1035 chore: bump by minor to v1.16.0
  package-lock.json
  package.json
Labels: maintenance

#967 feat(auth): Add JWT auth for API routes
  .github/workflows/dependency-review.yml
  config.schema.json
  package-lock.json
  package.json
  proxy.config.json
  src/config/index.ts
  src/config/types.ts
  src/service/passport/activeDirectory.js
  src/service/passport/index.js
  src/service/passport/jwtAuthHandler.js
  src/service/passport/local.js
  src/service/passport/oidc.js
  src/service/routes/index.js
  src/ui/auth/AuthProvider.tsx
  src/ui/components/RouteGuard/RouteGuard.tsx
Labels: feature

#1036 chore: bump by minor to v1.17.0
  package-lock.json
  package.json
Labels: maintenance
