Repository finos/git-proxy, pull requests merged in 2025-03, with the labels that each got.

#936 chore: bump by patch to 1.8.1
  package-lock.json
  package.json
Labels: maintenance

#906 feat: Preliminary OIDC implementation
  cypress.config.js
  cypress/e2e/login.cy.js
  package-lock.json
  package.json
  src/db/file/index.js
  src/db/file/users.js
  src/db/index.js
  src/service/passport/index.js
  src/service/passport/local.js
  src/service/passport/oidc.js
  src/service/routes/auth.js
  src/service/routes/users.js
  src/ui/views/Login/Login.jsx
Labels: feature

#937 chore: bump by minor to 1.9.0
  package-lock.json
  package.json
Labels: maintenance

#908 feat: Add support for executing pre-receive hooks
  package.json
  src/proxy/chain.js
  src/proxy/processors/push-action/index.js
  src/proxy/processors/push-action/preReceive.js
  test/chain.test.js
  test/preReceive/mock/repo/test-repo/Readme.md
  test/preReceive/pre-receive-hooks/always-allow.sh
  test/preReceive/pre-receive-hooks/always-reject.sh
  test/preReceive/preReceive.test.js
Labels: feature

#939 chore: bump by patch to 1.9.1
  package-lock.json
  package.json
Labels: maintenance

#945 fix: clean up .remote folder after tests and extend timeout
  test/testClearBareClone.test.js
Labels: fix

#949 chore: bump by patch to 1.9.2
  package-lock.json
  package.json
Labels: maintenance

#804 feat: Implemented search and pagination in Dashboard
  src/ui/components/Filtering/Filtering.css
  src/ui/components/Filtering/Filtering.jsx
  src/ui/components/Pagination/Pagination.css
  src/ui/components/Pagination/Pagination.jsx
  src/ui/components/Search/Search.css
  src/ui/components/Search/Search.jsx
  src/ui/views/OpenPushRequests/components/PushesTable.jsx
  src/ui/views/RepoList/Components/Repositories.jsx
  src/ui/views/UserList/Components/UserList.jsx
Labels: feature

#953 chore: bump by minor to 1.9.3
  package-lock.json
  package.json
Labels: maintenance

#957 fix: dashboard not displaying push data
  src/ui/views/OpenPushRequests/components/PushesTable.jsx
Labels: fix
