Repository finos/git-proxy, pull requests merged in 2025-09, with the labels that each got.

#1179 fix: render committer and author email links instead of estimated profile links
  src/types/models.ts
  src/ui/utils.tsx
  src/ui/views/OpenPushRequests/components/PushesTable.tsx
  src/ui/views/PushDetails/PushDetails.tsx
Labels: fix

#1109 test: improve repo DB tests and CheckRepoInAuthList tests
  src/db/file/repo.ts
  src/proxy/processors/push-action/checkRepoInAuthorisedList.ts
  test/db/file/repo.test.js
  test/db/mongo/repo.test.js
  test/processors/testCheckRepoInAuthList.test.js
  test/testCheckRepoInAuthList.test.js
Labels: fix, automation

#1140 refactor: migrate configuration system from JSON Schema to QuickType
  .eslintrc.json
  .github/workflows/lint.yml
  .github/workflows/unused-dependencies.yml
  config.schema.json
  package-lock.json
  package.json
  scripts/add-banner.ts
  src/config/ConfigLoader.ts
  src/config/file.ts
  src/config/generated/config.ts
  src/config/index.ts
  src/proxy/index.ts
  test/ConfigLoader.test.js
  test/generated-config.test.js
  test/proxy.test.js
  test/testConfig.test.js
Labels: automation

#1189 feat: push speed optimizations
  src/proxy/processors/push-action/checkAuthorEmails.ts
  src/proxy/processors/push-action/checkCommitMessages.ts
  src/proxy/processors/push-action/pullRemote.ts
  src/proxy/routes/index.ts
  src/service/routes/push.js
  test/processors/clearBareClone.test.js
Labels: feature

#1218 fix: linter warnings and CI failure
  cypress/e2e/autoApproved.cy.js
  cypress/e2e/repo.cy.js
  src/db/file/repo.ts
  src/db/index.ts
  src/proxy/routes/index.ts
  test/chain.test.js
  test/integration/forcePush.integration.test.js
  test/testProxy.test.js
Labels: fix

#1230 fix: "MongoServerError: The _id cannot be changed" when updating users
  src/db/mongo/users.ts
Labels: bug, fix

#1234 chore: remove defunct release workflow
  .github/workflows/release.yml
Labels: maintenance
