Repository finos/git-proxy, pull requests merged in 2025-06, with the labels that each got.

#1032 test: improve `config` test coverage
  src/config/ConfigLoader.ts
  test/ConfigLoader.test.js
  test/testConfig.test.js
Labels: automation

#1038 test: increase action test coverage
  package.json
  src/proxy/processors/push-action/checkAuthorEmails.ts
  src/proxy/processors/push-action/getDiff.ts
  src/proxy/processors/push-action/gitleaks.ts
  test/fixtures/gitleaks-config.toml
  test/plugin/plugin.test.js
  test/processors/blockForAuth.test.js
  test/processors/checkAuthorEmails.test.js
  test/processors/checkCommitMessages.test.js
  test/processors/checkIfWaitingAuth.test.js
  test/processors/checkUserPushPermission.test.js
  test/processors/clearBareClone.test.js
  test/processors/getDiff.test.js
  test/processors/gitLeaks.test.js
  test/processors/writePack.test.js
Labels: automation

#1046 fix: correct method for finding ad configuration
  src/service/passport/activeDirectory.js
Labels: fix

#1047 chore: bump by patch to v1.17.2
  package-lock.json
  package.json
Labels: maintenance

#1050 test: stop the config loader and restore defaults after tests have run
  test/ConfigLoader.test.js
Labels: automation

#1052 chore: apply finos active badge
  README.md
Labels: maintenance

#1048 feat(experimental): fall back to local spdx data and filter deprecated
  experimental/li-cli/package.json
  experimental/li-cli/src/cli.ts
  experimental/li-cli/src/cmds/add-license.ts
  experimental/li-cli/src/lib/chooseALicense.ts
  experimental/li-cli/src/lib/licenses.json
  experimental/li-cli/src/lib/spdx.ts
  experimental/li-cli/tsconfig.json
Labels: feature

#1025 test: improve proxy route test coverage
  src/proxy/routes/index.ts
  test/testProxyRoute.js
  test/testProxyRoute.test.js
  test/testRouteFilter.test.js
Labels: automation

#1059 chore: upgrade node in CI to 20.19
  .github/workflows/ci.yml
  .github/workflows/experimental-inventory-ci.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  test/plugin/plugin.test.js
  test/testUserCreation.test.js
Labels: maintenance
