Repository finos/git-proxy, pull requests merged in 2025-07, with the labels that each got.

#1061 fix: allow for auth with activedirectory again
  src/config/ConfigLoader.ts
  src/service/routes/auth.js
  test/ConfigLoader.test.js
Labels: fix

#1070 fix: correct typing for ConfigLoader env
  .github/workflows/ci.yml
  package.json
  src/config/ConfigLoader.ts
Labels: fix

#1099 chore: bump by minor to v1.19.0
  package-lock.json
  package.json
Labels: maintenance

#1093 fix: prevent non-admin users changing another user's gitAccount
  src/service/routes/auth.js
  test/services/routes/auth.test.js
Labels: fix

#1094 fix: only trim trailing .git not any match
  src/db/file/pushes.ts
  src/db/helper.ts
  src/db/mongo/pushes.ts
  src/proxy/processors/push-action/checkRepoInAuthorisedList.ts
  src/proxy/processors/push-action/checkUserPushPermission.ts
  src/ui/views/OpenPushRequests/components/PushesTable.tsx
  src/ui/views/PushDetails/PushDetails.tsx
  src/ui/views/RepoDetails/RepoDetails.tsx
  test/db-helper.test.js
  test/testDb.test.js
Labels: fix

#1098 fix: additional user api leaks
  src/service/routes/auth.js
  src/service/routes/index.js
  src/service/routes/publicApi.js
  src/service/routes/users.js
  test/services/routes/auth.test.js
Labels: fix

#1011 fix: updated URL for FINOS community slack channel
  README.md
Labels: documentation, fix

#1117 docs: update SECURITY.md with reporting guidance
  SECURITY.md
Labels: documentation

#1103 fix: dependency vulnerability fixes
  package-lock.json
  package.json
  test/checkHiddenCommit.test.js
  website/package.json
  website/yarn.lock
Labels: fix

#1118 fix: parsePush regression on tmp directory
  src/proxy/processors/push-action/parsePush.ts
Labels: fix

#1129 fix: restore user configs being merged with defaults
  index.ts
  src/config/index.ts
  test/testActiveDirectoryAuth.test.js
  test/testAuthMethods.test.js
  test/testConfig.test.js
Labels: fix
