Repository finos/git-proxy, pull requests merged in 2025-08, with the labels that each got.

#1137 chore: prepare for 2.x release with rc version
  package-lock.json
  package.json
Labels: maintenance

#1159 chore: update npm release workflow to handle pre-releases
  .github/workflows/npm.yml
Labels: maintenance

#1162 chore: bump version to rc.2
  package-lock.json
  package.json
  test/ConfigLoader.test.js
Labels: maintenance

#1096 feat: JWT `apiAuthentication` UI integration
  package-lock.json
  package.json
  src/constants/languageColors.ts
  src/routes.tsx
  src/service/passport/jwtAuthHandler.js
  src/ui/components/Card/Card.tsx
  src/ui/components/Card/CardAvatar.tsx
  src/ui/components/Card/CardBody.tsx
  src/ui/components/Card/CardFooter.tsx
  src/ui/components/Card/CardHeader.tsx
  src/ui/components/Card/CardIcon.tsx
  src/ui/components/CustomButtons/Button.tsx
  src/ui/components/CustomButtons/CodeActionButton.tsx
  src/ui/components/CustomInput/CustomInput.jsx
  src/ui/components/CustomTabs/CustomTabs.tsx
  src/ui/components/Navbars/DashboardNavbarLinks.tsx
  src/ui/components/Navbars/Navbar.tsx
  src/ui/components/Sidebar/Sidebar.tsx
  src/ui/components/Snackbar/Snackbar.tsx
  src/ui/components/Snackbar/SnackbarContent.tsx
  src/ui/components/Table/Table.jsx
  src/ui/components/Typography/Danger.jsx
  src/ui/components/Typography/Info.jsx
  src/ui/components/Typography/Muted.jsx
  src/ui/components/Typography/Primary.jsx
  src/ui/components/Typography/Quote.jsx
  src/ui/components/Typography/Success.jsx
  src/ui/components/Typography/Warning.jsx
  src/ui/services/auth.js
  src/ui/services/git-push.js
  src/ui/services/repo.js
  src/ui/services/user.ts
  src/ui/views/OpenPushRequests/OpenPushRequests.tsx
  src/ui/views/OpenPushRequests/components/PushesTable.tsx
  src/ui/views/RepoDetails/Components/AddUser.tsx
  src/ui/views/RepoList/Components/Repositories.tsx
  src/ui/views/Settings/Settings.jsx
  src/ui/views/User/User.tsx
  src/ui/views/UserList/Components/UserList.tsx
  test/testJwtAuthHandler.test.js
Labels: feature

#1154 test: fix Cypress test data dependency
  cypress.config.js
  cypress/e2e/repo.cy.js
  cypress/support/commands.js
  src/ui/components/Tasks/Tasks.jsx
  src/ui/services/repo.js
  test/processors/blockForAuth.test.js
  test/testCheckRepoInAuthList.test.js
Labels: automation

#1167 fix: mongoDB client impl issues
  src/db/file/repo.ts
  src/db/helper.ts
  src/db/mongo/repo.ts
  src/db/mongo/users.ts
Labels: bug, fix
